cleanup

diff --git a/.github/workflows/nightly.yml b/.github/workflows/nightly.yml
--- a/.github/workflows/nightly.yml
+++ b/.github/workflows/nightly.yml
@@ -314,8 +314,7 @@ jobs:
   performance-test:
     needs: [ matrix_prep, create-toolbox ]
     runs-on: ubuntu-latest
-    continue-on-error: true
-  
+
     steps:
       - name: Harden Runner
         uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
@@ -353,11 +352,6 @@ jobs:
           cbuild2cmake -V
           cbuildgen -V
 
-      - name: PRINT PACK_ROOT
-        working-directory: ./test
-        run: |
-          echo "$CMSIS_PACK_ROOT"
-
       - name: Activate Arm tool license
         run: |
           armlm activate --server https://mdk-preview.keil.arm.com --product KEMDK-COM0
@@ -368,7 +362,7 @@ jobs:
           sudo apt-get update
           sudo apt-get install -y hyperfine
 
-      - name: Clone All Examples
+      - name: Clone Input Examples
         shell: bash
         continue-on-error: true
         working-directory: ./test
@@ -386,26 +380,21 @@ jobs:
           path: ./test/test-reports-linux-amd64
           retention-days: ${{ env.retention-days }}
 
-      - name: Run benchmark with released binaries
-        working-directory: ./test
-        run: |
-          hyperfine --warmup 0 --min-runs 1 \
-            "cbuild setup ./old_test_dir/csolution-examples/Hello/Hello.csolution.yml -p -S --update-rte --toolchain AC6" \
-            "cbuild setup ./old_test_dir/vscode-get-started/get_started.csolution.yml -p -S --update-rte --toolchain AC6" \
-            --export-markdown released_benchmark_results.md \
-            --export-json released_benchmark_results.json \
-            --show-output
-
-      - name: Print released report
-        if: always()
-        working-directory: ./test
-        run: |
-          cat released_benchmark_results.md >> $GITHUB_STEP_SUMMARY
-
-      # - name: Delete example dir
+      # - name: Run old benchmark
       #   working-directory: ./test
       #   run: |
-      #     rm -rf performance_test_dir
+      #     hyperfine --warmup 0 --runs 1 \
+      #       "cbuild setup ./old_test_dir/csolution-examples/Hello/Hello.csolution.yml -p -S --update-rte --toolchain AC6" \
+      #       "cbuild setup ./old_test_dir/vscode-get-started/get_started.csolution.yml -p -S --update-rte --toolchain AC6" \
+      #       --export-markdown released_benchmark_results.md \
+      #       --export-json released_benchmark_results.json \
+      #       --show-output
+
+      # - name: Print old benchmark report
+      #   if: always()
+      #   working-directory: ./test
+      #   run: |
+      #     cat released_benchmark_results.md >> $GITHUB_STEP_SUMMARY
 
       - name: Download cmsis toolbox
         uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
@@ -423,7 +412,24 @@ jobs:
         shell: bash
         run: |
           echo "path=$(echo "$(pwd)/cmsis-toolbox/bin")" >> $GITHUB_OUTPUT
-  
+
+      - name: Run old benchmark
+        working-directory: ./test
+        run: |
+          export PATH="${{steps.toolbox_path.outputs.path}}:$PATH"
+          hyperfine --warmup 0 --runs 1 \
+            "cbuild setup ./old_test_dir/csolution-examples/Hello/Hello.csolution.yml -p -S --update-rte --toolchain AC6" \
+            "cbuild setup ./old_test_dir/vscode-get-started/get_started.csolution.yml -p -S --update-rte --toolchain AC6" \
+            --export-markdown released_benchmark_results.md \
+            --export-json released_benchmark_results.json \
+            --show-output
+
+      - name: Print old benchmark report
+        if: always()
+        working-directory: ./test
+        run: |
+          cat released_benchmark_results.md >> $GITHUB_STEP_SUMMARY
+          
       - name: Binary version info
         if: always()
         shell: bash
@@ -436,19 +442,7 @@ jobs:
           cbuild2cmake -V
           cbuildgen -V
 
-      # - name: Run Test
-      #   shell: bash
-      #   continue-on-error: true
-      #   working-directory: ./test
-      #   run: |
-      #     export PATH="${{steps.toolbox_path.outputs.path}}:$PATH"
-      #     robot --outputdir reports-linux-amd64 \
-      #       --variable OUTPUT_FILE:performance_record_linux_amd64.json \
-      #       --consolewidth=150 --settag linux-amd64 \
-      #       --name linux-amd64 \
-      #       ./performance_test.robot
-
-      - name: Clone All Examples
+      - name: Clone Input Examples
         shell: bash
         continue-on-error: true
         working-directory: ./test
@@ -460,57 +454,41 @@ jobs:
             --consolewidth=150 \
             ./performance_test.robot
 
-      - name: Run benchmarks
+      - name: Run new benchmarks
         working-directory: ./test
         run: |
           export PATH="${{steps.toolbox_path.outputs.path}}:$PATH"
           export CMSIS_PACK_ROOT="$(pwd)/local_pack_root"
-          hyperfine --warmup 0 --min-runs 1 \
+          hyperfine --warmup 0 --runs 1 \
             "cbuild setup ./new_test_dir/csolution-examples/Hello/Hello.csolution.yml -p -S --update-rte --toolchain AC6" \
             "cbuild setup ./new_test_dir/vscode-get-started/get_started.csolution.yml -p -S --update-rte --toolchain AC6" \
             --export-markdown curr_benchmark_results.md \
             --export-json curr_benchmark_results.json \
             --show-output
 
-      - name: Print Report
+      - name: Archive JSON Package
+        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
+        with:
+          name: test_json
+          path: ./test/curr_benchmark_results.json
+
+      - name: Print new report
         if: always()
         working-directory: ./test
         run: |
           cat curr_benchmark_results.md >> $GITHUB_STEP_SUMMARY
 
       - name: Compare Benchmark Results
-        run: python compare_hyperfine.py -r released_benchmark_results.json -c curr_benchmark_results.json
+        working-directory: ./test
+        run: |
+          python ./lib/check_performance.py -r released_benchmark_results.json -c curr_benchmark_results.json
 
-      # - name: Run Performance Check
-      #   run: |
-      #     python test/lib/check_performance.py -i ./test/performance_record_linux_amd64.json
-
-      # - name: Print Report
-      #   if: always()
-      #   shell: bash
-      #   run: |
-      #     cat performance_results.md >> $GITHUB_STEP_SUMMARY
-
-      # - name: TEMP performance results
-      #   if: always()
-      #   uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
-      #   with:
-      #     name: TEMP_linux_amd64
-      #     path: ./performance_results.md
-      #     retention-days: ${{ env.retention-days }}
-  
-      # - name: Archieve robot test results
-      #   if: always()
-      #   uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
-      #   with:
-      #     name: reports-linux-amd64
-      #     path: ./test/reports-linux-amd64
-      #     retention-days: ${{ env.retention-days }}
-
-      # - name: Archive performance results
-      #   if: always()
-      #   uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
-      #   with:
-      #     name: performance_record_linux_amd64
-      #     path: ./test/performance_record_linux_amd64.json
-      #     retention-days: ${{ env.retention-days }}
+  check-status:
+    needs: performance-test
+    if: ${{ needs.performance-test.result == 'failure' }}
+    runs-on: ubuntu-latest
+    steps:
+      - name: Fail if performance-test fails
+        run: |
+          echo "performance-test failed."
+          exit 1
